name: StoneAnalysis CI

on:
  push:
    branches: [ "main" ]

jobs:
  ci-and-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Push to Epitech
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Mirror to Epitech
        env:
          TARGET_REPO: git@github.com:EpitechPGE2-2025/G-CNA-400-MPL-4-1-stoneanalysis-1.git
        run: |
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git remote add epitech $TARGET_REPO
          git push epitech main --force